"""medical records documents ai analyses

Revision ID: 9fc23f4ceacd
Revises: 7dc0da81ebf9
Create Date: 2026-04-29 15:10:29.863329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc23f4ceacd'
down_revision = '7dc0da81ebf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('anamnesis', sa.Text(), nullable=False),
    sa.Column('physical_exam', sa.Text(), nullable=False),
    sa.Column('diagnostic_hypothesis', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('conduct', sa.Text(), nullable=False),
    sa.Column('prescriptions', sa.Text(), nullable=False),
    sa.Column('exams_requested', sa.Text(), nullable=False),
    sa.Column('evolution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_doctor_profile_id'), ['doctor_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_patient_id'), ['patient_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_medical_record_id'), ['medical_record_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ai_diagnosis', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=32), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('doctor_agreement', sa.Enum('YES', 'NO', 'PARTIAL', name='doctoragreementenum'), nullable=True),
    sa.Column('doctor_final_assessment', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_medical_record_id'), ['medical_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_medical_record_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_document_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_clinic_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_medical_record_id'))
        batch_op.drop_index(batch_op.f('ix_documents_clinic_id'))

    op.drop_table('documents')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_doctor_profile_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_appointment_id'))

    op.drop_table('medical_records')
    # ### end Alembic commands ###
